### ISSUE TITLE
Repository out of date

### ISSUE THREAD

**Issue by dotcom9** [angular-ui/bootstrap-bower#68]
It would be helpful to have more recent releases of this package available in this repository for Visual Studio users.

**Comment by icfantv** [comment]
@dotcom9. they are updated - most recently as of  yesterday with the 1.2.5 release.  what repo are you using?  Are you following [these instructions](https://github.com/angular-ui/bootstrap#install-with-bower)?

**Comment by xt0rted** [comment]
@icfantv they're probably referring to [angular-ui/bootstrap#install-with-nuget](https://github.com/angular-ui/bootstrap#install-with-nuget) and [Angular.UI.Bootstrap](https://www.nuget.org/packages/Angular.UI.Bootstrap/) which I've been maintaining on behalf of the angular ui team.

I no longer use NuGet for client-side packages. I also don't use Angular or this project anymore which is why the last few versions didn't go up as quickly as they used to.

I just published the missing versions so NuGet is up to date again.

**Comment by dotcom9** [comment]
Thanks @xt0rted but in fact, I'm using Bower and Visual Studio 2015 to install js packages. The package in question is angular-bootstrap. In the Manage Bower Packages tool that package is only available up to 0.13.4 (see attached screenshot). There is a bug in the carousel directive in that package so I want to install a later version.
![angular-bootstrap](https://cloud.githubusercontent.com/assets/4866561/13948458/085b6a42-f018-11e5-9a04-fd87cee95ab0.PNG)

**Comment by dotcom9** [comment]
I discovered though that despite the latest versions not appearing for selection, if I edit bower.json directly and use a later version number, it does download it correctly.

**Comment by icfantv** [comment]
@dotcom9, what bower.json file?  I'm looking at [this one](https://github.com/angular-ui/bootstrap-bower/blob/master/bower.json) and it's correct.

**Comment by dotcom9** [comment]
The one in my project declaring the .js dependencies that it has.

**Comment by craigbroadman** [comment]
Why is Visual Studio still only showing 0.13.4 in the bower package manager? As above, it works by changing the version in the bower.json file but this isn't ideal.

**Comment by xt0rted** [comment]
@craigbroadman this is a VS Tooling issue and needs to be followed up in https://github.com/aspnet/Tooling/issues/328
